AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy this to the account where the resources exist. Here we use CloudWatch Alarms and Logs as an example."

Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "Account1Role"
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - "222222222222"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AllowAccessToResources"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "cloudwatch:DeleteAlarms"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:PutMetricAlarm"
                Resource: !Sub "arn:aws:cloudwatch:us-east-*:${AWS::AccountId}:alarm:*"
