# This template to generate a Route53 Hosted Zone
# Execute this step first to retrieve the nameservers and migrate them from the domain registrar

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Domain:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "{{ host }}"
      HostedZoneConfig:
        Comment: "{{ description }}"

Outputs:
  Domain:
    Description: "NameServers"
    Value: !Join
      - ','
      - !GetAtt Domain.NameServers

